on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - run: |
        curl -LO https://mirror.ctan.org/systems/mac/mactex/BasicTeX.pkg
        sudo installer -pkg BasicTeX.pkg -target /
        rm BasicTeX.pkg
    - run: ls /usr/local/texlive/2023basic/bin/
    - run: echo "export PATH=/usr/local/texlive/2023basic/bin/universal-darwin:\$PATH" >> $GITHUB_ENV
    - run: |
        sudo tlmgr update --self
        sudo tlmgr install latexmk
    - run: latexmk -xelatex resume.tex
    - uses: actions/upload-artifact@v4
      with:
        name: resume
        path: resume.pdf
