name: main

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Install BasicTeX
      run: |
        curl -LO https://mirror.ctan.org/systems/mac/mactex/BasicTeX.pkg
        sudo installer -pkg BasicTeX.pkg -target /
        rm BasicTeX.pkg
        echo "/usr/local/texlive/2023basic/bin/universal-darwin" >> $GITHUB_PATH

    - name: Check BasicTeX installation
      run: tlmgr --version

    - name: Install latexmk and LaTeX packages
      run: |
        sudo tlmgr update --self
        sudo tlmgr install latexmk moderncv \
          academicons arydshln fontawesome5 multirow

    - if: github.ref_type != 'tag'
      name: Build resume
      run: latexmk -xelatex resume.tex
      env:
        VERSION: ${{ github.sha }}

    - if: github.ref_type == 'tag'
      name: Build resume
      run: latexmk -xelatex resume.tex
      env:
        VERSION: ${{ github.ref_name }}

    - if: github.ref_type != 'tag'
      name: Upload resume
      uses: actions/upload-artifact@v4
      with:
        name: jpvillaisaza-resume-${{ github.sha }}.pdf
        path: resume.pdf

    - if: github.ref_type == 'tag'
      name: Release resume
      uses: softprops/action-gh-release@v1
      with:
        files: jpvillaisaza-resume-${{ github.ref_name }}.pdf
        tag_name: ${{ github.ref_name }}
