name: main

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.05

    - if: github.ref_type != 'tag'
      name: Build resume
      run: nix-shell --run "latexmk -jobname=${{ env.JOB_NAME }} -xelatex resume.tex"
      env:
        JOB_NAME: jpvillaisaza-resume-${{ github.sha }}
        VERSION: ${{ github.sha }}

    - if: github.ref_type == 'tag'
      name: Build resume for tag
      run: nix-shell --run "latexmk -jobname=${{ env.JOB_NAME }} -xelatex resume.tex"
      env:
        JOB_NAME: jpvillaisaza-resume-${{ github.ref_name }}
        VERSION: ${{ github.ref_name }}

    - if: github.ref_type != 'tag'
      name: Upload resume
      uses: actions/upload-artifact@v4
      with:
        name: jpvillaisaza-resume-${{ github.sha }}
        path: jpvillaisaza-resume-${{ github.sha }}.pdf

    - if: github.ref_type == 'tag'
      name: Release resume
      uses: softprops/action-gh-release@v1
      with:
        files: jpvillaisaza-resume-${{ github.ref_name }}.pdf
        tag_name: ${{ github.ref_name }}
